angular.module('hackerAssessor.main', [])
  .controller('FormController', FormController)
  .factory('SkillService', SkillService)
  .factory('CategoryService', CategoryService)
  .factory('QuestionService', QuestionService)
