angular.module('hackerAssessor.main', [])
    .controller('ListController', ListController)
    .controller('UpdateController', UpdateController)
    .controller('CreateController', CreateController)
    .factory('HackerService', HackerService)
    .factory('QuestionService', QuestionService)
    .factory('HelperService', HelperService)
    .factory('SkillService', SkillService)
    .factory('CategoryService', CategoryService);